// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerfisdeInvestimento.Infrastructure.Data;

#nullable disable

namespace PerfisdeInvestimento.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117001648_SeedHistoricoInvestimentos")]
    partial class SeedHistoricoInvestimentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PerfisdeInvestimento.Domain.Entities.HistoricoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rentabilidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistoricosInvestimentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 123,
                            Data = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.12m,
                            Tipo = "CDB",
                            Valor = 5000.00m
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 123,
                            Data = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.08m,
                            Tipo = "Fundo Multimercado",
                            Valor = 3000.00m
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 456,
                            Data = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.14m,
                            Tipo = "LCI",
                            Valor = 8000.00m
                        });
                });

            modelBuilder.Entity("PerfisdeInvestimento.Domain.Entities.PerfilRisco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCalculo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoPerfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PerfisRisco");
                });

            modelBuilder.Entity("PerfisdeInvestimento.Domain.Entities.ProdutoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PerfilRecomendado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrazoMinimoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rentabilidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Risco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "CDB Caixa 2025",
                            PerfilRecomendado = "Conservador",
                            PrazoMinimoMeses = 6,
                            Rentabilidade = 0.12m,
                            Risco = "Baixo",
                            Tipo = "CDB",
                            ValorMinimo = 1000m
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Fundo de Investimento Caixa Assets",
                            PerfilRecomendado = "Agressivo",
                            PrazoMinimoMeses = 12,
                            Rentabilidade = 0.18m,
                            Risco = "Alto",
                            Tipo = "Fundo",
                            ValorMinimo = 10000m
                        },
                        new
                        {
                            Id = 3,
                            Nome = "LCI Imobiliário Caixa",
                            PerfilRecomendado = "Moderado",
                            PrazoMinimoMeses = 24,
                            Rentabilidade = 0.14m,
                            Risco = "Médio",
                            Tipo = "LCI",
                            ValorMinimo = 2000m
                        });
                });

            modelBuilder.Entity("PerfisdeInvestimento.Domain.Entities.SimulacaoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorInvestido")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("PerfisdeInvestimento.Domain.Entities.Telemetria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Telemetrias");
                });
#pragma warning restore 612, 618
        }
    }
}
